plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    id("org.jetbrains.kotlin.plugin.compose")
}

android {
    namespace = "com.opensiri.agent.bootstrap"
    compileSdk = 35

    defaultConfig {
        applicationId = "com.opensiri.agent.bootstrap"
        minSdk = 26
        // targetSdk 28 allows executing binaries from app data directory.
        // Android 10+ (targetSdk 29+) enforces W^X via SELinux which blocks
        // proot from executing Termux binaries. Termux (F-Droid) uses the same approach.
        // Note: Google Play rejects targetSdk < 34 — side-load only.
        targetSdk = 28
        versionCode = 2
        versionName = "0.2.0"
    }

    // ── Product flavors: bootstrap vs complete/offline ────────────────────
    // Bootstrap:  ~39 MB APK, downloads Termux deps on first launch
    // Complete:   ~225 MB APK, pre-bundles all deps (no internet needed)
    flavorDimensions += "edition"
    productFlavors {
        create("bootstrap") {
            dimension = "edition"
            applicationIdSuffix = ".bootstrap"
            versionNameSuffix = "-bootstrap"
        }
        create("complete") {
            dimension = "edition"
            applicationIdSuffix = ".complete"
            versionNameSuffix = "-complete"
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = false
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
        isCoreLibraryDesugaringEnabled = true
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    buildFeatures {
        compose = true
    }

    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }

    // Don't compress bootstrap zip, .deb packages, or .tar.gz bundles
    androidResources {
        noCompress += listOf("zip", "tar.gz", "deb")
    }

    // ── Flavor-specific asset configuration ───────────────────────────────
    // The complete flavor includes pre-bundled .deb packages (in assets/complete/)
    // generated by scripts/prebuild-complete.sh before the Gradle build.
    // The bootstrap flavor does NOT include these — it downloads deps on first launch.
    sourceSets {
        getByName("complete") {
            assets.srcDirs("src/main/assets", "src/complete/assets")
        }
    }
}

dependencies {
    // Core
    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.1.5")
    implementation("androidx.core:core-ktx:1.15.0")
    implementation("androidx.appcompat:appcompat:1.7.0")

    // Compose (Material 3)
    implementation(platform("androidx.compose:compose-bom:2025.01.00"))
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.material3:material3")
    implementation("androidx.compose.ui:ui-tooling-preview")
    implementation("androidx.compose.foundation:foundation")
    implementation("androidx.activity:activity-compose:1.9.3")
    implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.8.7")
    implementation("androidx.lifecycle:lifecycle-runtime-compose:2.8.7")

    // Material Design components
    implementation("com.google.android.material:material:1.12.0")

    // WebView
    implementation("androidx.webkit:webkit:1.12.1")

    // Testing (pure-JVM, no Robolectric)
    testImplementation("junit:junit:4.13.2")
}
